name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > mykey.pem
        chmod 600 mykey.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i mykey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/ec2-user/Hirirng_process/zdothire_backend &&
          git pull origin main &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          sudo systemctl restart zdothire_backend
        "
     