name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Setup SSH key
    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" | base64 --decode > mykey.pem
        chmod 400 mykey.pem

    # 3️⃣ Ensure SSH directory exists and add EC2 host to known_hosts
    - name: Add EC2 to known_hosts
      run: |
        mkdir -p $HOME/.ssh
        chmod 700 $HOME/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts
        chmod 644 $HOME/.ssh/known_hosts

    # 4️⃣ Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -i mykey.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
          set -e; \
          cd /home/ec2-user/Hirirng_process/zdothire_backend; \
          git reset --hard; \
          git pull origin main; \
          source venv/bin/activate; \
          pip install --upgrade pip; \
          pip install -r requirements.txt; \
          # Optional: run migrations and collectstatic
          # python manage.py migrate --noinput; \
          # python manage.py collectstatic --noinput; \
          sudo systemctl restart zdothire_backend; \
        "
